In [46]:
import pandas as pd

In [47]:
cafe = pd.read_csv('Python Project/dirty_cafe_sales.csv')

In [48]:
cafe

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [49]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [50]:
cafe.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [51]:
cafe.head()
cafe.sample(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
4196,TXN_7694559,Cookie,3,1.0,3.0,Cash,Takeaway,2023-05-05
2037,TXN_2578309,Smoothie,3,4.0,12.0,NaN,ERROR,2023-05-05
2772,TXN_7093219,Smoothie,4,4.0,16.0,Credit Card,NaN,2023-06-06
7033,TXN_7927109,Tea,1,1.5,1.5,Cash,NaN,2023-04-18
6001,TXN_2414686,Cake,1,3.0,3.0,Cash,NaN,ERROR
2205,TXN_2631671,Cookie,1,1.0,NaN,Credit Card,NaN,ERROR
8251,TXN_3745153,Smoothie,4,4.0,16.0,Digital Wallet,In-store,2023-06-30
9689,TXN_7002929,Cookie,1,1.0,1.0,NaN,In-store,2023-01-30
4110,TXN_9107508,Coffee,1,2.0,2.0,NaN,NaN,2023-06-06
692,TXN_5476465,Cake,NaN,3.0,12.0,Cash,In-store,2023-06-23
40,TXN_2083138,Smoothie,3,4.0,12.0,NaN,In-store,2023-04-17
7401,TXN_3486548,Tea,1,1.5,1.5,Digital Wallet,NaN,2023-07-08
6411,TXN_9213505,Sandwich,2,4.0,8.0,UNKNOWN,NaN,2023-11-01
8975,TXN_8077367,Tea,NaN,UNKNOWN,7.5,Credit Card,NaN,2023-02-27
6105,TXN_4172649,Salad,4,5.0,20.0,Digital Wallet,NaN,2023-05-19
9329,TXN_6785331,Cake,1,3.0,3.0,NaN,NaN,2023-04-12
4114,TXN_7887682,UNKNOWN,2,2.0,4.0,Credit Card,Takeaway,2023-06-17
4383,TXN_5927925,Juice,4,3.0,12.0,Digital Wallet,In-store,2023-11-02
2214,TXN_2452624,Juice,1,3.0,3.0,Cash,NaN,2023-11-10
8491,TXN_8265257,Coffee,1,2.0,2.0,ERROR,In-store,2023-10-25

In [52]:
cafe.columns = cafe.columns.str.strip().str.upper().str.replace(' ', '_')

In [53]:
cafe

,TRANSACTION_ID,ITEM,QUANTITY,PRICE_PER_UNIT,TOTAL_SPENT,PAYMENT_METHOD,LOCATION,TRANSACTION_DATE
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [54]:
cafe.select_dtypes(include='object').columns

Index(['TRANSACTION_ID', 'ITEM', 'QUANTITY', 'PRICE_PER_UNIT', 'TOTAL_SPENT',
       'PAYMENT_METHOD', 'LOCATION', 'TRANSACTION_DATE'],
      dtype='object')

In [55]:
for col in cafe.select_dtypes(include='object').columns:
    cafe[col] = cafe[col].str.strip().str.title()

In [56]:
cafe.isnull().sum()

TRANSACTION_ID         0
ITEM                 333
QUANTITY             138
PRICE_PER_UNIT       179
TOTAL_SPENT          173
PAYMENT_METHOD      2579
LOCATION            3265
TRANSACTION_DATE     159
dtype: int64

In [57]:
cafe['QUANTITY'] = pd.to_numeric(cafe['QUANTITY'], errors='coerce')
cafe['PRICE_PER_UNIT'] = pd.to_numeric(cafe['PRICE_PER_UNIT'].replace('[₦,]', '', regex=True), errors='coerce')
cafe['TOTAL_SPENT'] = pd.to_numeric(cafe['TOTAL_SPENT'].replace('[₦,]', '', regex=True), errors='coerce')

In [58]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TRANSACTION_ID    10000 non-null  object
 1   ITEM              9667 non-null   object
 2   QUANTITY          9521 non-null   float64
 3   PRICE_PER_UNIT    9467 non-null   float64
 4   TOTAL_SPENT       9498 non-null   float64
 5   PAYMENT_METHOD    7421 non-null   object
 6   LOCATION          6735 non-null   object
 7   TRANSACTION_DATE  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

In [59]:
cafe.duplicated().value_counts()

False    10000
Name: count, dtype: int64

In [60]:
import numpy as np
from collections import defaultdict
item_price_map = {
    'Cake': 3.0,
    'Cookie': 1.0,
    'Coffee': 2.0,
    'Juice': 3.0,
    'Salad': 5.0,
    'Sandwich': 4.0,
    'Smoothie': 4.0,
    'Tea': 1.5
}
price_to_items = defaultdict(list)
for item, price in item_price_map.items():
    price_to_items[price].append(item)


def fill_item_price(row):
    item = row['ITEM']
    price = row['PRICE_PER_UNIT']

    # Step 1 — item is missing/bad but price exists → reverse lookup
    if (pd.isna(item) or item in ['', 'Unknown', 'Error']) and pd.notna(price):
        if price in price_to_items:
            return np.random.choice(price_to_items[price]), price
        else:
            return item, price

    # Step 2 — price is missing/bad but item is valid → forward lookup
    elif (pd.isna(price) or price in ['Unknown', 'Error', '']) and item in item_price_map:
        correct_price = item_price_map[item]
        return item, correct_price

    # Step 3 — both fine, return as-is
    else:
        return item, price

cafe[['ITEM', 'PRICE_PER_UNIT']] = cafe.apply(lambda row: pd.Series(fill_item_price(row)), axis=1)

In [61]:
cafe[['ITEM', 'PRICE_PER_UNIT']].isnull().sum()

ITEM              23
PRICE_PER_UNIT    54
dtype: int64

In [62]:
# Count unique values in ITEM
print(cafe['ITEM'].value_counts(dropna=False))

# Count unique values in PRICE_PER_UNIT
print(cafe['PRICE_PER_UNIT'].value_counts(dropna=False))

ITEM
Juice       1304
Coffee      1284
Salad       1270
Cake        1240
Sandwich    1238
Cookie      1209
Smoothie    1202
Tea         1199
NaN           23
Unknown       18
Error         13
Name: count, dtype: int64
PRICE_PER_UNIT
3.0    2544
4.0    2440
2.0    1284
5.0    1270
1.0    1209
1.5    1199
NaN      54
Name: count, dtype: int64

In [63]:
cafe[(cafe['ITEM'].isin(['', 'Unknown', 'Error'])) | 
     (cafe['PRICE_PER_UNIT'].isin(['', 'Unknown', 'Error']) | cafe['PRICE_PER_UNIT'].isna())]

,TRANSACTION_ID,ITEM,QUANTITY,PRICE_PER_UNIT,TOTAL_SPENT,PAYMENT_METHOD,LOCATION,TRANSACTION_DATE
118,Txn_4633784,Error,5.0,NaN,15.0,NaN,In-Store,2023-02-06
151,Txn_4031509,NaN,4.0,NaN,16.0,Credit Card,Takeaway,2023-01-04
289,Txn_3495950,NaN,4.0,NaN,6.0,Credit Card,In-Store,2023-02-19
334,Txn_2523298,NaN,4.0,NaN,6.0,Error,In-Store,2023-03-25
550,Txn_4186681,Error,4.0,NaN,6.0,Digital Wallet,NaN,2023-05-24
750,Txn_5787508,Error,3.0,NaN,9.0,Credit Card,Takeaway,2023-07-23
818,Txn_7940202,NaN,1.0,NaN,4.0,Digital Wallet,NaN,2023-07-23
1154,Txn_2473090,Unknown,2.0,NaN,3.0,Credit Card,In-Store,2023-03-03
1337,Txn_5031214,Error,5.0,NaN,5.0,NaN,Takeaway,2023-07-29
1377,Txn_8396271,Error,2.0,NaN,2.0,NaN,NaN,2023-09-12
1589,Txn_5245399,NaN,5.0,NaN,10.0,NaN,NaN,2023-12-25
1761,Txn_3611851,NaN,4.0,NaN,NaN,Credit Card,NaN,2023-02-09
1786,Txn_1923349,Error,4.0,NaN,6.0,NaN,NaN,2023-07-06
2002,Txn_5206049,NaN,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-24
2227,Txn_3200203,Error,2.0,NaN,8.0,NaN,Unknown,2023-12-04
2289,Txn_7524977,Unknown,4.0,NaN,NaN,Error,NaN,2023-12-09
2596,Txn_4844386,NaN,5.0,NaN,15.0,Credit Card,In-Store,2023-10-28
2610,Txn_8266689,NaN,5.0,NaN,15.0,Cash,In-Store,2023-12-03
2962,Txn_9702662,Unknown,4.0,NaN,16.0,NaN,Takeaway,2023-07-10
3013,Txn_1842697,Unknown,5.0,NaN,15.0,NaN,NaN,2023-10-25
3404,Txn_7797231,NaN,5.0,NaN,10.0,Digital Wallet,NaN,2023-05-05
3434,Txn_6457997,Unknown,1.0,NaN,4.0,Credit Card,NaN,2023-12-12
3666,Txn_8616276,Unknown,2.0,NaN,3.0,Digital Wallet,Takeaway,2023-07-22
3739,Txn_4849180,Unknown,5.0,NaN,15.0,Credit Card,In-Store,2023-10-14
3779,Txn_7376255,Unknown,NaN,NaN,25.0,NaN,In-Store,2023-05-27
3900,Txn_5093855,NaN,4.0,NaN,6.0,Cash,Takeaway,2023-11-23
4092,Txn_1840897,Unknown,1.0,NaN,5.0,Error,NaN,2023-06-03
4152,Txn_9646000,Error,2.0,NaN,NaN,NaN,In-Store,2023-12-14
4621,Txn_7844352,Error,2.0,NaN,6.0,Credit Card,NaN,2023-07-26
5039,Txn_9514452,Error,5.0,NaN,10.0,Credit Card,Takeaway,2023-07-29
5891,Txn_9618962,NaN,3.0,NaN,6.0,Credit Card,Takeaway,2023-11-08
5991,Txn_2913107,Unknown,4.0,NaN,8.0,NaN,In-Store,2023-05-20
6177,Txn_3232279,Unknown,4.0,NaN,16.0,Unknown,Takeaway,2023-05-30
6345,Txn_4208919,NaN,3.0,NaN,12.0,NaN,Takeaway,2023-05-30
6429,Txn_2536573,NaN,2.0,NaN,8.0,Cash,In-Store,2023-06-24
6849,Txn_7928378,NaN,3.0,NaN,12.0,Cash,NaN,2023-07-04
7478,Txn_9710982,Unknown,4.0,NaN,16.0,NaN,NaN,2023-03-03
7597,Txn_1082717,Error,NaN,NaN,9.0,Digital Wallet,In-Store,2023-12-13
8129,Txn_8384699,Unknown,3.0,NaN,15.0,NaN,In-Store,2023-12-16
8458,Txn_7595907,NaN,5.0,NaN,15.0,NaN,In-Store,2023-04-24
8463,Txn_2150872,Unknown,5.0,NaN,15.0,Cash,Takeaway,2023-03-18
8817,Txn_8365530,NaN,4.0,NaN,16.0,NaN,Takeaway,2023-03-10
8959,Txn_3803063,NaN,4.0,NaN,12.0,Credit Card,Takeaway,2023-11-23
9174,Txn_5935353,NaN,2.0,NaN,8.0,Credit Card,Error,2023-05-01
9234,Txn_8918253,Unknown,3.0,NaN,12.0,Digital Wallet,NaN,2023-09-07
9382,Txn_4255580,Error,1.0,NaN,3.0,Cash,NaN,NaN
9425,Txn_2065683,Unknown,3.0,NaN,6.0,NaN,NaN,2023-09-21
9454,Txn_1637131,Error,4.0,NaN,6.0,Cash,NaN,Unknown
9673,Txn_2480808,Unknown,1.0,NaN,4.0,Credit Card,NaN,2023-03-30
9717,Txn_3334632,NaN,1.0,NaN,2.0,Credit Card,Takeaway,2023-11-20
9764,Txn_1688292,Unknown,3.0,NaN,9.0,Credit Card,In-Store,NaN
9819,Txn_1208561,NaN,NaN,NaN,20.0,Credit Card,NaN,2023-08-19
9820,Txn_8751702,NaN,5.0,NaN,15.0,Cash,NaN,2023-02-13
9996,Txn_9659401,NaN,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-02

In [64]:
# rows where total_spent can help recover quantity
mask1 = cafe['TOTAL_SPENT'].notna() & cafe['PRICE_PER_UNIT'].notna() & cafe['QUANTITY'].isna()

# rows where total_spent can help recover price
mask2 = cafe['TOTAL_SPENT'].notna() & cafe['QUANTITY'].notna() & cafe['PRICE_PER_UNIT'].isna()

print(mask1.sum(), "rows where quantity can be derived")
print(mask2.sum(), "rows where price can be derived")

456 rows where quantity can be derived
48 rows where price can be derived

In [65]:
# how many of the bad item rows have total_spent to work with
mask_item_bad = cafe['ITEM'].isna() | cafe['ITEM'].isin(['', 'Unknown', 'Error'])

print(cafe[mask_item_bad][['ITEM', 'QUANTITY', 'PRICE_PER_UNIT', 'TOTAL_SPENT']].isna().sum())
print()
print("rows with total_spent available:", cafe[mask_item_bad]['TOTAL_SPENT'].notna().sum())
print("rows with price available:", cafe[mask_item_bad]['PRICE_PER_UNIT'].notna().sum())
print("rows with quantity available:", cafe[mask_item_bad]['QUANTITY'].notna().sum())

ITEM              23
QUANTITY           3
PRICE_PER_UNIT    54
TOTAL_SPENT        3
dtype: int64

rows with total_spent available: 51
rows with price available: 0
rows with quantity available: 51

In [66]:
mask_item_bad = cafe['ITEM'].isna() | cafe['ITEM'].isin(['', 'Unknown', 'Error'])

# Step 1 — recover price_per_unit from total_spent / quantity for the 51 rows
mask_derive_price = mask_item_bad & cafe['TOTAL_SPENT'].notna() & cafe['QUANTITY'].notna() & cafe['PRICE_PER_UNIT'].isna()
cafe.loc[mask_derive_price, 'PRICE_PER_UNIT'] = (
    cafe.loc[mask_derive_price, 'TOTAL_SPENT'] / cafe.loc[mask_derive_price, 'QUANTITY']
).round(2)

# Step 2 — reverse lookup item using the now-recovered price
def recover_item(row):
    item = row['ITEM']
    price = row['PRICE_PER_UNIT']
    if (pd.isna(item) or item in ['', 'Unknown', 'Error']) and pd.notna(price):
        if price in price_to_items:
            return np.random.choice(price_to_items[price])
    return item

cafe['ITEM'] = cafe.apply(recover_item, axis=1)

# Step 3 — the remaining 3 where everything is missing → random fill
mask_still_bad = cafe['ITEM'].isna() | cafe['ITEM'].isin(['', 'Unknown', 'Error'])
print("Rows still needing random fill:", mask_still_bad.sum())

Rows still needing random fill: 6

In [67]:
# after deriving price
cafe.loc[mask_derive_price, 'PRICE_PER_UNIT'] = (
    cafe.loc[mask_derive_price, 'TOTAL_SPENT'] / cafe.loc[mask_derive_price, 'QUANTITY']
).round(2)

# after deriving quantity
mask_derive_qty = cafe['TOTAL_SPENT'].notna() & cafe['PRICE_PER_UNIT'].notna() & cafe['QUANTITY'].isna()
cafe.loc[mask_derive_qty, 'QUANTITY'] = (
    cafe.loc[mask_derive_qty, 'TOTAL_SPENT'] / cafe.loc[mask_derive_qty, 'PRICE_PER_UNIT']
).round().astype(int)

# enforce integer type on the whole column at the end
cafe['QUANTITY'] = cafe['QUANTITY'].round().astype('Int64')

In [68]:
cafe[(cafe['ITEM'].isin(['', 'Unknown', 'Error'])) | 
     (cafe['PRICE_PER_UNIT'].isin(['', 'Unknown', 'Error']) | cafe['PRICE_PER_UNIT'].isna())]

,TRANSACTION_ID,ITEM,QUANTITY,PRICE_PER_UNIT,TOTAL_SPENT,PAYMENT_METHOD,LOCATION,TRANSACTION_DATE
1761,Txn_3611851,NaN,4,NaN,NaN,Credit Card,NaN,2023-02-09
2289,Txn_7524977,Unknown,4,NaN,NaN,Error,NaN,2023-12-09
3779,Txn_7376255,Unknown,<NA>,NaN,25.0,NaN,In-Store,2023-05-27
4152,Txn_9646000,Error,2,NaN,NaN,NaN,In-Store,2023-12-14
7597,Txn_1082717,Error,<NA>,NaN,9.0,Digital Wallet,In-Store,2023-12-13
9819,Txn_1208561,NaN,<NA>,NaN,20.0,Credit Card,NaN,2023-08-19

In [71]:
for col in ['ITEM', 'QUANTITY', 'PRICE_PER_UNIT', 'TOTAL_SPENT']:
    print(cafe[col].value_counts(dropna=False))
    print()

ITEM
Juice       1312
Coffee      1291
Salad       1272
Cake        1245
Sandwich    1245
Cookie      1213
Smoothie    1209
Tea         1207
NaN            2
Unknown        2
Error          2
Name: count, dtype: int64

QUANTITY
5       2108
2       2056
3       1946
4       1941
1       1926
<NA>      23
Name: count, dtype: Int64

PRICE_PER_UNIT
3.0    2557
4.0    2454
2.0    1291
5.0    1272
1.0    1213
1.5    1207
NaN       6
Name: count, dtype: int64

TOTAL_SPENT
6.0     979
12.0    939
3.0     930
4.0     923
20.0    746
15.0    734
8.0     677
10.0    524
NaN     502
2.0     497
9.0     479
5.0     468
16.0    444
25.0    259
7.5     237
1.0     232
4.5     225
1.5     205
Name: count, dtype: int64

In [72]:
# filter rows where any of the 4 columns have issues
mask = (
    cafe['ITEM'].isna() | cafe['ITEM'].isin(['', 'Unknown', 'Error']) |
    cafe['QUANTITY'].isna() |
    cafe['PRICE_PER_UNIT'].isna() |
    cafe['TOTAL_SPENT'].isna()
)

print(cafe[mask][['ITEM', 'QUANTITY', 'PRICE_PER_UNIT', 'TOTAL_SPENT']])
print()
print("Total affected rows:", mask.sum())

          ITEM  QUANTITY  PRICE_PER_UNIT  TOTAL_SPENT
2       Cookie         4             1.0          NaN
25    Smoothie         3             4.0          NaN
31      Cookie         2             1.0          NaN
42         Tea         2             1.5          NaN
65    Sandwich         3             4.0          NaN
...        ...       ...             ...          ...
9893     Juice         2             3.0          NaN
9954    Coffee         4             2.0          NaN
9977     Juice         2             3.0          NaN
9988      Cake         5             3.0          NaN
9993  Smoothie         2             4.0          NaN

[505 rows x 4 columns]

Total affected rows: 505

In [73]:
# inspect the 6 problematic rows
mask = cafe['ITEM'].isna() | cafe['ITEM'].isin(['', 'Unknown', 'Error'])
print(cafe[mask][['ITEM', 'QUANTITY', 'PRICE_PER_UNIT', 'TOTAL_SPENT']])

         ITEM  QUANTITY  PRICE_PER_UNIT  TOTAL_SPENT
1761      NaN         4             NaN          NaN
2289  Unknown         4             NaN          NaN
3779  Unknown      <NA>             NaN         25.0
4152    Error         2             NaN          NaN
7597    Error      <NA>             NaN          9.0
9819      NaN      <NA>             NaN         20.0

In [74]:
# Step 1 — random fill item + price for all 6
mask_bad = cafe['ITEM'].isna() | cafe['ITEM'].isin(['', 'Unknown', 'Error'])

def fill_unrecoverable(row):
    item = row['ITEM']
    if pd.isna(item) or item in ['', 'Unknown', 'Error']:
        random_item = np.random.choice(list(item_price_map.keys()))
        random_price = item_price_map[random_item]
        return random_item, random_price
    return item, row['PRICE_PER_UNIT']

cafe.loc[mask_bad, ['ITEM', 'PRICE_PER_UNIT']] = cafe[mask_bad].apply(
    lambda row: pd.Series(fill_unrecoverable(row)), axis=1).values

# Step 2 — recover quantity for rows 3779, 7597, 9819 using total_spent / price
mask_derive_qty = cafe['QUANTITY'].isna() & cafe['TOTAL_SPENT'].notna() & cafe['PRICE_PER_UNIT'].notna()
cafe.loc[mask_derive_qty, 'QUANTITY'] = (
    cafe.loc[mask_derive_qty, 'TOTAL_SPENT'] / cafe.loc[mask_derive_qty, 'PRICE_PER_UNIT']
).round().astype(int)

# Step 3 — verify
print(cafe[['ITEM', 'QUANTITY', 'PRICE_PER_UNIT']].isna().sum())

ITEM               0
QUANTITY          20
PRICE_PER_UNIT     0
dtype: int64

In [76]:
# check the distribution first
print(cafe['QUANTITY'].value_counts().sort_index())

QUANTITY
1    1926
2    2057
3    1946
4    1942
5    2108
6       1
Name: count, dtype: Int64

In [77]:
# fix the rogue 6
cafe.loc[cafe['QUANTITY'] == 6, 'QUANTITY'] = 5

# fill the 20 missing with mode
cafe['QUANTITY'] = cafe['QUANTITY'].fillna(5).astype('Int64')

# derive TOTAL_SPENT
cafe['TOTAL_SPENT'] = cafe['QUANTITY'] * cafe['PRICE_PER_UNIT']

# verify
print("QUANTITY missing:", cafe['QUANTITY'].isna().sum())
print("TOTAL_SPENT missing:", cafe['TOTAL_SPENT'].isna().sum())

QUANTITY missing: 0
TOTAL_SPENT missing: 0

In [79]:
for col in ['LOCATION', 'PAYMENT_METHOD']:
    print(cafe[col].value_counts(dropna=False))
    print()

LOCATION
NaN         3265
Takeaway    3022
In-Store    3017
Error        358
Unknown      338
Name: count, dtype: int64

PAYMENT_METHOD
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
Error              306
Unknown            293
Name: count, dtype: int64

In [81]:
# fill location proportionally
loc_valid = cafe[cafe['LOCATION'].isin(['Takeaway', 'In-Store'])]['LOCATION']
loc_counts = loc_valid.value_counts(normalize=True)
loc_mask = cafe['LOCATION'].isna() | cafe['LOCATION'].isin(['Error', 'Unknown'])

cafe.loc[loc_mask, 'LOCATION'] = np.random.choice(
    loc_counts.index.tolist(),
    size=loc_mask.sum(),
    replace=True,
    p=loc_counts.values
)

# fill payment method proportionally
pay_valid = cafe[cafe['PAYMENT_METHOD'].isin(['Digital Wallet', 'Credit Card', 'Cash'])]['PAYMENT_METHOD']
pay_counts = pay_valid.value_counts(normalize=True)
pay_mask = cafe['PAYMENT_METHOD'].isna() | cafe['PAYMENT_METHOD'].isin(['Error'])

cafe.loc[pay_mask, 'PAYMENT_METHOD'] = np.random.choice(
    pay_counts.index.tolist(),
    size=pay_mask.sum(),
    replace=True,
    p=pay_counts.values
)

# verify
print(cafe['LOCATION'].value_counts())
print()
print(cafe['PAYMENT_METHOD'].value_counts())

LOCATION
Takeaway    5055
In-Store    4945
Name: count, dtype: int64

PAYMENT_METHOD
Cash              3297
Digital Wallet    3269
Credit Card       3141
Unknown            293
Name: count, dtype: int64

In [82]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TRANSACTION_ID    10000 non-null  object
 1   ITEM              10000 non-null  object
 2   QUANTITY          10000 non-null  Int64
 3   PRICE_PER_UNIT    10000 non-null  float64
 4   TOTAL_SPENT       10000 non-null  Float64
 5   PAYMENT_METHOD    10000 non-null  object
 6   LOCATION          10000 non-null  object
 7   TRANSACTION_DATE  9841 non-null   object
dtypes: Float64(1), Int64(1), float64(1), object(5)
memory usage: 644.7+ KB

In [83]:
print(cafe['TRANSACTION_DATE'].head(20))

0     2023-09-08
1     2023-05-16
2     2023-07-19
3     2023-04-27
4     2023-06-11
5     2023-03-31
6     2023-10-06
7     2023-10-28
8     2023-07-28
9     2023-12-31
10    2023-11-07
11         Error
12    2023-05-03
13    2023-06-01
14    2023-03-21
15    2023-11-15
16    2023-06-10
17    2023-02-24
18    2023-03-25
19    2023-01-15
Name: TRANSACTION_DATE, dtype: object

In [84]:
print(cafe['TRANSACTION_DATE'].value_counts(dropna=False))
print()
print("NaN:", cafe['TRANSACTION_DATE'].isna().sum())
print("Error:", (cafe['TRANSACTION_DATE'] == 'Error').sum())
print("Unknown:", (cafe['TRANSACTION_DATE'] == 'Unknown').sum())

TRANSACTION_DATE
Unknown       159
NaN           159
Error         142
2023-06-16     40
2023-02-06     40
             ...
2023-04-27     15
2023-09-24     15
2023-07-22     14
2023-03-11     14
2023-02-17     14
Name: count, Length: 368, dtype: int64

NaN: 159
Error: 142
Unknown: 159

In [85]:
# replace Error and Unknown with NaN
cafe['TRANSACTION_DATE'] = cafe['TRANSACTION_DATE'].replace(['Error', 'Unknown'], np.nan)

# convert to datetime (coerce catches anything else that's unparseable)
cafe['TRANSACTION_DATE'] = pd.to_datetime(cafe['TRANSACTION_DATE'], errors='coerce')

# verify
print("Total undated rows:", cafe['TRANSACTION_DATE'].isna().sum())

Total undated rows: 460

In [86]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TRANSACTION_ID    10000 non-null  object
 1   ITEM              10000 non-null  object
 2   QUANTITY          10000 non-null  Int64
 3   PRICE_PER_UNIT    10000 non-null  float64
 4   TOTAL_SPENT       10000 non-null  Float64
 5   PAYMENT_METHOD    10000 non-null  object
 6   LOCATION          10000 non-null  object
 7   TRANSACTION_DATE  9540 non-null   datetime64[ns]
dtypes: Float64(1), Int64(1), datetime64[ns](1), float64(1), object(4)
memory usage: 644.7+ KB

In [87]:
cafe

,TRANSACTION_ID,ITEM,QUANTITY,PRICE_PER_UNIT,TOTAL_SPENT,PAYMENT_METHOD,LOCATION,TRANSACTION_DATE
0,Txn_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,Txn_4977031,Cake,4,3.0,12.0,Cash,In-Store,2023-05-16
2,Txn_4271903,Cookie,4,1.0,4.0,Credit Card,In-Store,2023-07-19
3,Txn_7034554,Salad,2,5.0,10.0,Unknown,Takeaway,2023-04-27
4,Txn_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-Store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,Txn_7672686,Coffee,2,2.0,4.0,Credit Card,In-Store,2023-08-30
9996,Txn_9659401,Cookie,3,1.0,3.0,Digital Wallet,Takeaway,2023-06-02
9997,Txn_5255387,Coffee,4,2.0,8.0,Digital Wallet,In-Store,2023-03-02
9998,Txn_7695629,Cookie,3,1.0,3.0,Digital Wallet,In-Store,2023-12-02
9999,Txn_6170729,Sandwich,3,4.0,12.0,Cash,In-Store,2023-11-07